wip: evolving build to run tests with uTest
does not yet work.
Getting errors below.

Seems to be caused by the fact that the build downloads sbt plugin version 0.5.4 instead of 0.6.0-M3

[info] Compiling 2 Scala sources to /home/nickdsc/projects/playframework-learn/scalajs-tutorial/project/target/scala-2.10/sbt-0.13/classes...
[error] /home/nickdsc/projects/playframework-learn/scalajs-tutorial/project/Build.scala:117: value %%% is not a member of String
[error]       "com.lihaoyi" %%% "upickle" % "0.2.5",
[error]                     ^
[error] /home/nickdsc/projects/playframework-learn/scalajs-tutorial/project/Build.scala:118: value %%% is not a member of String
[error]       "com.lihaoyi" %%% "autowire" % "0.2.3")
[error]                     ^
[error] /home/nickdsc/projects/playframework-learn/scalajs-tutorial/project/Build.scala:74: value %%%! is not a member of String
[error]     libraryDependencies += "com.lihaoyi" %%%! "utest" % Plugin.utestVersion % "test"
[error]                                          ^
[error] /home/nickdsc/projects/playframework-learn/scalajs-tutorial/project/Build.scala:84: value %%% is not a member of String
[error]         "org.scala-lang.modules.scalajs" %%% "scalajs-dom" % "0.6",
[error]                                          ^
[error] /home/nickdsc/projects/playframework-learn/scalajs-tutorial/project/Build.scala:100: value %%% is not a member of String
[error]         "com.scalatags" %%% "scalatags" % "0.4.2"
[error]                         ^